apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-server
  labels:
    apps: login-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-server
  template:
    metadata:
      labels:
        app: login-server
    spec:
      containers:
      - name: login-server
        image: sydsh19/anchor_login_server:1.1
        ports:
        - containerPort: 8080