apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-cronjob
spec:
  schedule: "* 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: djmitsu/anchor-crawler:1.1
          restartPolicy: OnFailure
